import { Profile } from "./types";

export const mockProfiles: Profile[] = [
  {
    id: "1",
    first_name: "さくら",
    last_name: null,
    name_reading: "サクラ",
    age: 25,
    gender: "female",
    city: "東京",
    avatar_url: require("./assets/profiles/profile1.jpg"),
    description: "こんにちは！よろしくお願いします。",
    nationality: "日本",
    is_online: true,
    updated_at: null,
  },
  {
    id: "2",
    first_name: "あやか",
    last_name: null,
    name_reading: "アヤカ",
    age: 29,
    gender: "female",
    city: "大阪",
    avatar_url: require("./assets/profiles/profile2.jpg"),
    description: "大阪出身です。よろしくお願いします！",
    nationality: "日本",
    is_online: false,
    updated_at: null,
  },
  {
    id: "3",
    first_name: "ゆい",
    last_name: null,
    name_reading: "ユイ",
    age: 27,
    gender: "female",
    city: "京都",
    avatar_url: require("./assets/profiles/profile3.jpg"),
    description: "京都の美しい街が大好きです。",
    nationality: "日本",
    is_online: true,
    updated_at: null,
  },
  {
    id: "4",
    first_name: "みか",
    last_name: null,
    name_reading: "ミカ",
    age: 26,
    gender: "female",
    city: "横浜",
    avatar_url: require("./assets/profiles/profile4.jpg"),
    description: "横浜でお仕事しています。",
    nationality: "日本",
    is_online: false,
    updated_at: null,
  },
  {
    id: "5",
    first_name: "えみ",
    last_name: null,
    name_reading: "エミ",
    age: 24,
    gender: "female",
    city: "名古屋",
    avatar_url: require("./assets/profiles/profile5.jpg"),
    description: "名古屋のグルメが大好き！",
    nationality: "日本",
    is_online: true,
    updated_at: null,
  },
  {
    id: "6",
    first_name: "りな",
    last_name: null,
    name_reading: "リナ",
    age: 31,
    gender: "female",
    city: "神戸",
    avatar_url: require("./assets/profiles/profile6.jpg"),
    description: "神戸でのんびり暮らしています。",
    nationality: "日本",
    is_online: false,
    updated_at: null,
  },
  {
    id: "7",
    first_name: "まい",
    last_name: null,
    name_reading: "マイ",
    age: 26,
    gender: "female",
    city: "福岡",
    avatar_url: require("./assets/profiles/profile7.jpg"),
    description: "福岡出身です。明太子が大好き！",
    nationality: "日本",
    is_online: false,
    updated_at: null,
  },
  {
    id: "8",
    first_name: "なな",
    last_name: null,
    name_reading: "ナナ",
    age: 25,
    gender: "female",
    city: "札幌",
    avatar_url: require("./assets/profiles/profile8.jpg"),
    description: "北海道の自然が大好きです。",
    nationality: "日本",
    is_online: true,
    updated_at: null,
  },
];
